/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tableroller;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Time;
import java.time.LocalTime;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author aaron
 */
public class TableRollerGUI extends javax.swing.JFrame
  {

  public static Random generator;
  public static String[][][] weaponCharts;
  public static String[][] punctureCriticalChart;
  public static String[] weaponNames;
  public static int[] fumbleRanges;
  public static String[] weaponFileNames;
  public static String[] weaponTypes;

  /**
   * Creates new form TableRollerGUI
   */
  public TableRollerGUI()
    {
    initComponents();
    generator = new Random();
    
    punctureCriticalChart = new String[101][5]; //row 0 is not used    
    loadWeaponCharts();
    loadCritCharts();
    }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    TabPanel = new javax.swing.JTabbedPane();
    PlanetGenPanel = new javax.swing.JPanel();
    numPlanetsSpinner = new javax.swing.JSpinner();
    numPlanetsLabel = new javax.swing.JLabel();
    planetGenButton = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    planetGenTextArea = new javax.swing.JTextArea();
    planetSaveButton = new javax.swing.JButton();
    rollmasterWeaponPanel = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    RMActionTypeCB = new javax.swing.JComboBox<>();
    jLabel3 = new javax.swing.JLabel();
    RMWeaponSelectCB = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    RMWeaponSkillBonus = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    RMSpecialItemBonus = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    RMBonus = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    RMActivityNotUsed = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    RMDefenseBonus = new javax.swing.JTextField();
    RMRollButton = new javax.swing.JButton();
    RMResultScrollPane = new javax.swing.JScrollPane();
    RMResultTextArea = new javax.swing.JTextArea();
    jLabel2 = new javax.swing.JLabel();
    RMTargetArmor = new javax.swing.JTextField();
    RMThrownCB = new javax.swing.JCheckBox();
    RMMountedCB = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Table Roller");

    numPlanetsSpinner.setValue(1);

    numPlanetsLabel.setText("Planets to Generate:");

    planetGenButton.setText("Generate!");
    planetGenButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        planetGenButtonMouseClicked(evt);
      }
    });

    planetGenTextArea.setColumns(20);
    planetGenTextArea.setRows(5);
    jScrollPane1.setViewportView(planetGenTextArea);

    planetSaveButton.setText("Save Generated Planets");
    planetSaveButton.setEnabled(false);
    planetSaveButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        planetSaveButtonMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout PlanetGenPanelLayout = new javax.swing.GroupLayout(PlanetGenPanel);
    PlanetGenPanel.setLayout(PlanetGenPanelLayout);
    PlanetGenPanelLayout.setHorizontalGroup(
      PlanetGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
      .addGroup(PlanetGenPanelLayout.createSequentialGroup()
        .addComponent(planetSaveButton)
        .addGap(0, 226, Short.MAX_VALUE))
      .addGroup(PlanetGenPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(numPlanetsLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(numPlanetsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(planetGenButton)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    PlanetGenPanelLayout.setVerticalGroup(
      PlanetGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PlanetGenPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(PlanetGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(numPlanetsLabel)
          .addComponent(numPlanetsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(planetGenButton))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(planetSaveButton))
    );

    TabPanel.addTab("Planet Gen", PlanetGenPanel);

    jLabel1.setText("Type of Action:");

    RMActionTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Snap", "Normal", "Deliberate" }));
    RMActionTypeCB.setSelectedIndex(1);

    jLabel3.setText("Weapon:");

    RMWeaponSelectCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Two_Handed_Sword" }));

    jLabel4.setText("Skill Bonus:");

    RMWeaponSkillBonus.setText("0");

    jLabel5.setText("Special Item Bonus:");

    RMSpecialItemBonus.setText("0");

    jLabel6.setText("Penalties/Bonuses:");

    RMBonus.setText("0");

    jLabel7.setText("Activity Not Used:");

    RMActivityNotUsed.setText("0");

    jLabel8.setText("Defense Bonus:");

    RMDefenseBonus.setText("0");

    RMRollButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    RMRollButton.setText("ROLL!");
    RMRollButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        RMRollButtonMouseClicked(evt);
      }
    });

    RMResultTextArea.setColumns(20);
    RMResultTextArea.setRows(5);
    RMResultScrollPane.setViewportView(RMResultTextArea);

    jLabel2.setText("Target Armor:");

    RMTargetArmor.setText("1");
    RMTargetArmor.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        RMTargetArmorActionPerformed(evt);
      }
    });

    RMThrownCB.setText("Thrown?");
    RMThrownCB.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        RMThrownCBActionPerformed(evt);
      }
    });

    RMMountedCB.setText("Mounted?");
    RMMountedCB.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        RMMountedCBActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout rollmasterWeaponPanelLayout = new javax.swing.GroupLayout(rollmasterWeaponPanel);
    rollmasterWeaponPanel.setLayout(rollmasterWeaponPanelLayout);
    rollmasterWeaponPanelLayout.setHorizontalGroup(
      rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(rollmasterWeaponPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(RMResultScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(RMRollButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(rollmasterWeaponPanelLayout.createSequentialGroup()
            .addGroup(rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(rollmasterWeaponPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RMActionTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RMTargetArmor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(rollmasterWeaponPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RMWeaponSelectCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RMThrownCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RMMountedCB))
              .addGroup(rollmasterWeaponPanelLayout.createSequentialGroup()
                .addGroup(rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jLabel4)
                  .addComponent(jLabel6)
                  .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(RMDefenseBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(rollmasterWeaponPanelLayout.createSequentialGroup()
                    .addComponent(RMBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(RMActivityNotUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(rollmasterWeaponPanelLayout.createSequentialGroup()
                    .addComponent(RMWeaponSkillBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(RMSpecialItemBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGap(0, 35, Short.MAX_VALUE)))
        .addContainerGap())
    );
    rollmasterWeaponPanelLayout.setVerticalGroup(
      rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(rollmasterWeaponPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(RMActionTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addComponent(RMTargetArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(RMWeaponSelectCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(RMThrownCB)
          .addComponent(RMMountedCB))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(RMWeaponSkillBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5)
          .addComponent(RMSpecialItemBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(RMBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7)
          .addComponent(RMActivityNotUsed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(rollmasterWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8)
          .addComponent(RMDefenseBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(40, 40, 40)
        .addComponent(RMRollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(RMResultScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        .addContainerGap())
    );

    TabPanel.addTab("Rollmaster P1", rollmasterWeaponPanel);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(TabPanel)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(TabPanel)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /*
    This function calls generatePlanet a number of times equal to the value in the
    numPlanetsSpinner.
   */
    private void planetGenButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_planetGenButtonMouseClicked
    {//GEN-HEADEREND:event_planetGenButtonMouseClicked
      planetSaveButton.setEnabled(true);
      String output = "";
      int numPlanets = Integer.parseInt(numPlanetsSpinner.getValue().toString());

      //always generate at least 1 planet
      numPlanets = (numPlanets < 1) ? 1 : numPlanets;

      JFileChooser fileChooser = new JFileChooser("masterFiles");
      fileChooser.setDialogTitle("Select Master File");
      String defaultFilename = "masterFiles\\PlanetGenList.txt";
      fileChooser.setSelectedFile(new File(defaultFilename));

      int selection = fileChooser.showOpenDialog(null);

      if (selection == JFileChooser.APPROVE_OPTION)
        {
        File masterFile = fileChooser.getSelectedFile();
        //output += "Generating " + numPlanets + " planets!\n";
        for (int i = 0; i < numPlanets; i++)
          {
          output += "Planet " + i + ":\n" + generatePlanet(masterFile) + "\n";
          }
        }

      planetGenTextArea.setText(output);
    }//GEN-LAST:event_planetGenButtonMouseClicked

  /*
    This function writes the generated planets to a text file.
    
    TODO: Allow user to specify filename.
   */
    private void planetSaveButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_planetSaveButtonMouseClicked
    {//GEN-HEADEREND:event_planetSaveButtonMouseClicked
      JFileChooser fileChooser = new JFileChooser(".");
      fileChooser.setDialogTitle("Save");

      int selection = fileChooser.showSaveDialog(null);

      if (selection == JFileChooser.APPROVE_OPTION)
        {
        try
          {
          File filename = fileChooser.getSelectedFile();
          FileWriter outFile = new FileWriter(filename + ".txt");
          outFile.write(planetGenTextArea.getText());
          outFile.close();
          }
        catch (IOException ex)
          {
          Logger.getLogger(TableRollerGUI.class.getName()).log(Level.SEVERE, null, ex);
          }
        }
    }//GEN-LAST:event_planetSaveButtonMouseClicked

    private void RMRollButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMRollButtonMouseClicked
      //pull info from the combo boxes and text areas
      
      String actionType = RMActionTypeCB.getSelectedItem().toString(); 
      //Set modifier based on action type selected
      int actionModifier = 0; //default for normal action
      if(actionType.equals("Snap"))
        actionModifier = -20;
      else if(actionType.equals("Deliberate"))
        actionModifier = 10;
      
      //Get the weapon's index and max fumble value
      String weapon = RMWeaponSelectCB.getSelectedItem().toString();
      int weaponIndex = findWeaponIndex(weapon);
      int fumbleMax = getFumbleMax(weaponIndex);
      
      int skillBonus = Integer.parseInt(RMWeaponSkillBonus.getText().toString());
      int specialItemBonus = Integer.parseInt(RMSpecialItemBonus.getText().toString());

      int bonus = Integer.parseInt(RMBonus.getText());
      int activity = Integer.parseInt(RMActivityNotUsed.getText());
      int defenseBonus = Integer.parseInt(RMDefenseBonus.getText());
      
      int targetArmor = Integer.parseInt(RMTargetArmor.getText().toString());

      //start by rolling d100
      int roll = rollDie(100);

      RMResultTextArea.setText(""); //clear info from previous rolls
      RMResultTextArea.append("Base Roll = " + roll + "\n");

      //check for fumble
      if (roll < fumbleMax)
        {
        RMResultTextArea.append("\nFUMBLE\n\n");
        String type = weaponTypes[weaponIndex];
        RMResultTextArea.append("Weapon type is " + type + "\n");
        if(RMThrownCB.isSelected())
          {
          type = "Thrown";
          RMResultTextArea.append("Override: Weapon was thrown\n");
          }
        else if(RMMountedCB.isSelected())
          {
          type = "Mounted";
          RMResultTextArea.append("Override: User is mounted\n");
          }
        //TODO: Roll on fumble chart
        
        return; //nothing else to do
        }
      else if (roll <= 5) //check for open-ended low
        {
        int lowRoll;
        RMResultTextArea.append("\nOpen Ended Low\n\n");
        do
          {
          lowRoll = rollDie(100);
          roll -= lowRoll;
          RMResultTextArea.append("New Roll = " + lowRoll + "\n");
          }
        while(lowRoll > 96);
        RMResultTextArea.append("Final base roll = " + roll + "\n");
        }//end of open-ended low      
      else if (roll >= 96) //check for open-ended high roll
        {
        int highRoll;
        RMResultTextArea.append("\nOpen Ended High\n\n");
        do
          {
          highRoll = rollDie(100);
          roll += highRoll;
          RMResultTextArea.append("New Roll = " + highRoll + "\n");
          }
        while(highRoll > 96);
        RMResultTextArea.append("Final base roll = " + roll + "\n");
        }

      roll += skillBonus + specialItemBonus + bonus + activity - defenseBonus;
      RMResultTextArea.append("Final roll = " + roll + "\n");
      
      //clamp roll to [1, 150]
      roll = (roll < 1) ? 1 : roll;
      roll = (roll > 150) ? 150 : roll;
      
      String result = weaponCharts[weaponIndex][roll][targetArmor-1];
      RMResultTextArea.append("Result = " + result + "\n");
      
      //check if a crit has occurred. If so, cross reference in the appropriate chart.
      String[] exResult = result.split(" ");
      if(exResult.length > 1) //A crit has occurred
        {
        //exResult has 3 values: the damage (a number), the crit column (letter), and crit chart (letter)
        RMResultTextArea.append("=== CRITICAL HIT ===\n");
        RMResultTextArea.append("Base Damage: " + exResult[0] + "\n");
        RMResultTextArea.append("Column: " + exResult[1] + "\n");
        RMResultTextArea.append("Crit Type: " + exResult[2] + "\n");
        }
      else
        RMResultTextArea.append("Target takes " + result + " damage.\n");
    }//GEN-LAST:event_RMRollButtonMouseClicked

    
  private int findWeaponIndex(String weapon)
    {
    int index = 0;
    boolean foundIt = false;
    
    while(!foundIt && index < weaponNames.length)
      {
      if(weaponNames[index].equals(weapon))
        foundIt = true;
      else
        index++;
      }    
    
    if(foundIt)
      return index;
    else //should never trigger, if it does something went horribly wrong
      {
      Logger.getLogger(TableRollerGUI.class.getName()).log(Level.SEVERE, null, "ERROR: Weapon fumble range not found!");
      System.exit(1);
      return -1;
      }
    }//end of findWeaponIndex
  
  /* 
    Get max fumble value for a weapon, given its index into the fumble table
  */
  private int getFumbleMax(int index)
    {
    return fumbleRanges[index];    
    }//end of findFumbleMax
          
  private void RMTargetArmorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RMTargetArmorActionPerformed
  {//GEN-HEADEREND:event_RMTargetArmorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_RMTargetArmorActionPerformed

  private void RMThrownCBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RMThrownCBActionPerformed
  {//GEN-HEADEREND:event_RMThrownCBActionPerformed
    //Only one of the two checkboxes can be selected
    if(RMMountedCB.isSelected())
      RMMountedCB.setSelected(false);
  }//GEN-LAST:event_RMThrownCBActionPerformed

  private void RMMountedCBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RMMountedCBActionPerformed
  {//GEN-HEADEREND:event_RMMountedCBActionPerformed
    //Only one of the two checkboxes can be selected
    if(RMThrownCB.isSelected())
      RMThrownCB.setSelected(false);
  }//GEN-LAST:event_RMMountedCBActionPerformed

  /*
    This function reads in the planet generation master file, which contains the
    filenames of the tables to be rolled on. For each file listed, it calls the
    processPlanetFile function.
    
    TODO: Change hardcoded filename to allow user to choose master file.
   */
  public String generatePlanet(File masterFile)
    {
    String output = "";

    Scanner sc;
    try
      {
      sc = new Scanner(masterFile);

      int numFiles = sc.nextInt();
      sc.nextLine();
      for (int i = 0; i < numFiles; i++)
        {
        String filename = sc.nextLine();
        //output += filename + "\n";

        output += processPlanetFile(filename) + "\n";
        }
      sc.close();
      }
    catch (FileNotFoundException ex)
      {
      Logger.getLogger(TableRollerGUI.class.getName()).log(Level.SEVERE, null, ex);
      }

    return output;
    }//end of generatePlanet

  /*
    This function processes one planet file. The assumed file format is as follows:
    Line 1: Two values
        The number of dice to roll
        The size of die used
    Lines 2-n: One value per line, the table value for a given die roll
   */
  public String processPlanetFile(String filename)
    {
    String output = "";

    try
      {
      Scanner sc = new Scanner(new File(filename));

      String[] line = sc.nextLine().split(" ");
      int numDice = Integer.parseInt(line[0]);
      int dieFaces = Integer.parseInt(line[1]);

      int roll = 0;
      for (int i = 0; i < numDice; i++)
        {
        roll += rollDie(dieFaces);
        }

      //output += "total roll: " + roll + "\n";
      //NOTE: minimum possible value = number of dice rolled
      //Ex: 2d6 - min value is 2
      int maxValue = numDice * dieFaces;

      int row = numDice;
      while (sc.hasNextLine() && row != roll)
        {
        sc.nextLine();
        row++;
        }

      output += sc.nextLine();
      sc.close();
      }
    catch (FileNotFoundException ex)
      {
      Logger.getLogger(TableRollerGUI.class.getName()).log(Level.SEVERE, null, ex);
      }

    return output;
    }//end of processPlanetFile

  /*
    This function rolls a die with the specified number of sides and returns the result.
   */
  public int rollDie(int faces)
    {
    return generator.nextInt(faces) + 1;
    }//end of rollDie
  
  public void loadWeaponCharts()
    {
    int numWeapons = countWeapons();
    Scanner sc;
    
    //All charts are 150 x 20, but we ignore row 0
    weaponCharts = new String[numWeapons][151][20];
    weaponNames = new String[numWeapons];
    fumbleRanges = new int[numWeapons];
    weaponFileNames = new String[numWeapons];
    weaponTypes = new String[numWeapons];
    
    //For each weapon, load fumble ranges, add weapon to the dropdown box, and load the attack chart
    RMWeaponSelectCB.removeAllItems();
    try
      {
      sc = new Scanner(new File("masterFiles\\RM_WeaponInfo.txt"));
      
      int i = 0;
      while(sc.hasNextLine())
        {
        String[] s = sc.nextLine().split(" ");
        RMWeaponSelectCB.addItem(s[0]);
        weaponNames[i] = s[0];
        fumbleRanges[i] = Integer.parseInt(s[1]);
        weaponFileNames[i] = s[2]; 
        weaponTypes[i] = s[3];
        loadWeaponFile(i);
        i++;
        }
      
      sc.close();      
      }
    catch(FileNotFoundException ex)
      {
      Logger.getLogger(TableRollerGUI.class.getName()).log(Level.SEVERE, null, ex);
      System.exit(1);
      }       
    }//end of loadWeaponCharts
  
  //count number of weapons in the master file
  private int countWeapons()
    {
    Scanner sc;
    int numWeapons = 0;
    
    try
      {
      sc = new Scanner(new File("masterFiles\\RM_WeaponInfo.txt"));      
      
      while(sc.hasNextLine())
        {
        sc.nextLine();
        numWeapons++;
        }
      sc.close();
      }//end of try
    catch (FileNotFoundException ex)
      {
      Logger.getLogger(TableRollerGUI.class.getName()).log(Level.SEVERE, null, ex);
      System.exit(1); 
      }//end of catch
    
    //System.out.println("There are " + numWeapons + " weapons");
    return numWeapons;
    }
  
  private void loadWeaponFile(int index)
    {
    String filename = weaponFileNames[index];
    try
      {
      Scanner sc = new Scanner(new File(filename));

      int row = 1; //chart starts at 1, not 0
      while (sc.hasNextLine())
        {
        weaponCharts[index][row++] = sc.nextLine().split(",");
        
        //RMResultTextArea.append(weaponCharts[index][row][0] + "\n");
        }
      
      sc.close();
      }
    catch (FileNotFoundException ex)
      {
      Logger.getLogger(TableRollerGUI.class.getName()).log(Level.SEVERE, null, ex);
      System.exit(1);
      }
    }//end of loadWeaponFile
  
  public void loadCritCharts()
    {
    Scanner sc;
    //load puncture critical chart 
    try
      {
      sc = new Scanner(new File("tables\\PunctureCrit.csv"));

      int row = 1; //chart starts at 1, not 0
      while (sc.hasNextLine())
        {
        punctureCriticalChart[row++] = sc.nextLine().split(",");               
        }
      
      sc.close();
      }
    catch (FileNotFoundException ex)
      {
      Logger.getLogger(TableRollerGUI.class.getName()).log(Level.SEVERE, null, ex);
      System.exit(1);
      }
    
    
    }//end of loadCritCharts

  public static void main(String args[])
    {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
      {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
        {
        if ("Nimbus".equals(info.getName()))
          {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
          }
        }
      }
    catch (ClassNotFoundException ex)
      {
      java.util.logging.Logger.getLogger(TableRollerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
    catch (InstantiationException ex)
      {
      java.util.logging.Logger.getLogger(TableRollerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
    catch (IllegalAccessException ex)
      {
      java.util.logging.Logger.getLogger(TableRollerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
      java.util.logging.Logger.getLogger(TableRollerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
      {
      public void run()
        {
        new TableRollerGUI().setVisible(true);
        }
      });
    }//end of main

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel PlanetGenPanel;
  private javax.swing.JComboBox<String> RMActionTypeCB;
  private javax.swing.JTextField RMActivityNotUsed;
  private javax.swing.JTextField RMBonus;
  private javax.swing.JTextField RMDefenseBonus;
  private javax.swing.JCheckBox RMMountedCB;
  private javax.swing.JScrollPane RMResultScrollPane;
  private javax.swing.JTextArea RMResultTextArea;
  private javax.swing.JButton RMRollButton;
  private javax.swing.JTextField RMSpecialItemBonus;
  private javax.swing.JTextField RMTargetArmor;
  private javax.swing.JCheckBox RMThrownCB;
  private javax.swing.JComboBox<String> RMWeaponSelectCB;
  private javax.swing.JTextField RMWeaponSkillBonus;
  private javax.swing.JTabbedPane TabPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel numPlanetsLabel;
  private javax.swing.JSpinner numPlanetsSpinner;
  private javax.swing.JButton planetGenButton;
  private javax.swing.JTextArea planetGenTextArea;
  private javax.swing.JButton planetSaveButton;
  private javax.swing.JPanel rollmasterWeaponPanel;
  // End of variables declaration//GEN-END:variables
    }//end of class
